set(_CATKIN_CURRENT_PACKAGE "ssl-vision")
set(ssl-vision_VERSION "0.0.0")
set(ssl-vision_MAINTAINER "arpit <arpit@todo.todo>")
set(ssl-vision_PACKAGE_FORMAT "1")
set(ssl-vision_BUILD_DEPENDS "roscpp" "rospy" "std_msgs")
set(ssl-vision_BUILD_EXPORT_DEPENDS "roscpp" "rospy" "std_msgs")
set(ssl-vision_BUILDTOOL_DEPENDS "catkin")
set(ssl-vision_BUILDTOOL_EXPORT_DEPENDS )
set(ssl-vision_EXEC_DEPENDS "roscpp" "rospy" "std_msgs")
set(ssl-vision_RUN_DEPENDS "roscpp" "rospy" "std_msgs")
set(ssl-vision_TEST_DEPENDS )
set(ssl-vision_DOC_DEPENDS )
set(ssl-vision_URL_WEBSITE "")
set(ssl-vision_URL_BUGTRACKER "")
set(ssl-vision_URL_REPOSITORY "")
set(ssl-vision_DEPRECATED "")